import '@/app/globals.css'
import SideBar from '@/components/custom/SideBar'
import { Toaster } from '@/components/ui/toaster'
import { getCurrentUser } from '@/lib/getCurrentUser'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
   const {username}=await getCurrentUser()
  return (
    <html lang="en">
      <body>
      <div className="grid grid-rows-[80px_1fr] md:grid-cols-[250px_1fr]">
          <SideBar username={username}/>
          <div className="md:grid md:grid-cols-[80vw_1fr]">
          {children}
          <div className="hidden md:block">
  
          </div>
          </div>
          <Toaster/>
        </div>

      </body>
    </html>
  )
}
